name: Bug Report
description: Report a bug or issue with Flodoc
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Flodoc is affected?
      options:
        - MDX Rendering
        - Flow Visualization
        - Navigation/Routing
        - Search
        - Dark Mode
        - UI/Styling
        - Build/Development
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (blocks usage)
        - High (major feature broken)
        - Medium (annoying but workaround exists)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      value: |
        - OS: [e.g., macOS 14.0]
        - Browser: [e.g., Chrome 120]
        - Node/Bun Version: [e.g., Bun 1.3.1]
        - Flodoc Version: [e.g., 0.2.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Any relevant console logs or error messages
      placeholder: Paste console output here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Screenshots, related issues, etc.
